# Generated by Django 4.1 on 2022-10-18 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Advertisement/')),
                ('mainbanner', models.BooleanField(default=False)),
                ('centerbanner', models.BooleanField(default=False)),
                ('hero_banner', models.BooleanField(default=False)),
                ('small_banner', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('record_status', models.CharField(default='created', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_created_id', to=settings.AUTH_USER_MODEL)),
                ('modified_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_modified_id', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_product', to='product.product')),
            ],
        ),
    ]
