# Generated by Django 4.1 on 2022-10-18 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('product_totel_stoke', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('record_status', models.CharField(blank=True, default='created', max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reference_sub_category', to='category.category')),
                ('created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products_created_id', to=settings.AUTH_USER_MODEL)),
                ('main_category', models.ManyToManyField(related_name='product_reference_gender', to='category.gendercategory')),
                ('modified_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products_modified_id', to=settings.AUTH_USER_MODEL)),
                ('product_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reference_brand', to='category.brand')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='SubProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=product.models.sub_upload_image_path)),
                ('images2', models.ImageField(blank=True, null=True, upload_to=product.models.sub_upload_image_path)),
                ('images3', models.ImageField(blank=True, null=True, upload_to=product.models.sub_upload_image_path)),
                ('images4', models.ImageField(blank=True, null=True, upload_to=product.models.sub_upload_image_path)),
                ('images5', models.ImageField(blank=True, null=True, upload_to=product.models.sub_upload_image_path)),
                ('images6', models.ImageField(blank=True, null=True, upload_to=product.models.sub_upload_image_path)),
                ('sub_product_totel_stoke', models.IntegerField(blank=True, default=0, null=True)),
                ('sku', models.CharField(blank=True, max_length=355, null=True, unique=True)),
                ('offerprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('offer_persentage', models.FloatField(blank=True, null=True)),
                ('offer_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('record_status', models.CharField(blank=True, default='created', max_length=255, null=True)),
                ('created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_Products_created_id', to=settings.AUTH_USER_MODEL)),
                ('modified_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_Products_modified_id', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_product_reference_main_product', to='product.product')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_color_reference_sub_product', to='category.color')),
            ],
            options={
                'verbose_name_plural': 'sub Product Attribute',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=product.models.review_upload_image_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('record_status', models.CharField(blank=True, default='created', max_length=255, null=True)),
                ('created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_Products_review_created_id', to=settings.AUTH_USER_MODEL)),
                ('modified_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_Products_review_modified_id', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_review_referece_offer_product', to='product.subproductattribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('stock', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('record_status', models.CharField(blank=True, default='created', max_length=255, null=True)),
                ('created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_Products_quantity_created_id', to=settings.AUTH_USER_MODEL)),
                ('modified_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_Products_quantity_modified_id', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Quantity_referece_offer_product', to='product.subproductattribute')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_size_reference_sub_product', to='category.size')),
            ],
            options={
                'verbose_name_plural': 'Product Quantity',
            },
        ),
    ]
