# Generated by Django 4.1 on 2022-10-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='is_active',
            new_name='now_is_active',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='alt_phone_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
