# Generated by Django 4.1 on 2022-10-18 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('record_status', models.CharField(default='created', max_length=255)),
                ('created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cancel_created_id', to=settings.AUTH_USER_MODEL)),
                ('modified_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cancel_modified_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('product_qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totel_unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totel_qty_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_product', to='product.subproductattribute')),
                ('product_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_product_quantity', to='product.productquantity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_is_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('persentage_off', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gtr_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minus_pers', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('record_status', models.CharField(blank=True, default='created', max_length=255, null=True)),
                ('created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Coupon_created_id', to=settings.AUTH_USER_MODEL)),
                ('modified_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Coupon_modified_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_confirmation_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('orders_id', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('totel_quantity', models.IntegerField(default=1)),
                ('totel_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('totel_offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('offer_savings_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('coupon_text', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('coupon_savings_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, max_length=255, null=True)),
                ('totel_payment_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('coupen_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_order_coupen_is_auth', to='cart.coupon')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order_address_is_auth', to='accounts.useraddress')),
                ('products', models.ManyToManyField(related_name='products', to='cart.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_order_is_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedeamCoupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_redeam_coupen_is_auth', to='cart.coupon')),
                ('created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_redeam_coupen_is_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_confirmed', models.BooleanField(default=False)),
                ('order_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('Shipped', models.BooleanField(default=False)),
                ('Shipped_date', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('out_for_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_execept_date', models.DateField(blank=True, null=True)),
                ('Cancelled', models.BooleanField(default=False)),
                ('cancel_reason_descrition', models.TextField(blank=True, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('cancelReasons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_order_CancelReasons_status', to='cart.cancelreasons')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_order_status', to='cart.order')),
            ],
        ),
    ]
